#!/usr/bin/env bash
set -e

# Sudo _explicitly_ filters out PYTHONPATH, even when env_reset is disabled. but we want it
[[ $UID == ${ASTRONOMER_UID:-1000} ]] || exec sudo -H -u ${ASTRONOMER_USER} PYTHONPATH=$PYTHONPATH "$0" "$@"
# Make sure logs folder is writable by the right user.
[ -O "$AIRFLOW_HOME/logs" ] || sudo chown $ASTRONOMER_USER "$AIRFLOW_HOME/logs"

# Airflow subcommand
CMD=$2

url_parse_regex="[^:]+://([^@/]*@)?([^/:]*):?([0-9]*)/?"

# Wait for postgres then init the db
if [[ -n $AIRFLOW__CORE__SQL_ALCHEMY_CONN  ]]; then
  # Wait for database port to open up
  [[ ${AIRFLOW__CORE__SQL_ALCHEMY_CONN} =~ $url_parse_regex ]]
  HOST=${BASH_REMATCH[2]}
  PORT=${BASH_REMATCH[3]}
  echo "Waiting for host: ${HOST} ${PORT}"
  while ! nc -w 1 -z "${HOST}" "${PORT}"; do
    sleep 0.001
  done
fi

if [[ -n $AIRFLOW__CELERY__BROKER_URL ]] && [[ $CMD =~ ^(scheduler|worker|flower)$ ]]; then
  # Wait for database port to open up
  [[ ${AIRFLOW__CELERY__BROKER_URL} =~ $url_parse_regex ]]
  HOST=${BASH_REMATCH[2]}
  PORT=${BASH_REMATCH[3]}
  echo "Waiting for host: ${HOST} ${PORT}"
  while ! nc -w 1 -z "${HOST}" "${PORT}"; do
    sleep 0.001
  done
fi

# Run the original command
exec "$@"
