#
# Copyright 2019 Astronomer Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG baseimage=astronomerinc/ap-airflow:1.10.7-alpine3.10

FROM ${baseimage}

LABEL maintainer="Astronomer <humans@astronomer.io>"

LABEL io.astronomer.docker=true
LABEL io.astronomer.docker.airflow.onbuild=true

# Install alpine packages
ONBUILD COPY packages.txt .
ONBUILD RUN cat packages.txt | xargs apk add --no-cache

# Install python packages
ONBUILD COPY requirements.txt .
ONBUILD RUN if grep -Eqx 'apache-airflow[=~>]{1,2}.*' requirements.txt; then \
    echo >&2 "Do not upgrade by specifying 'apache-airflow' in your requirements.txt, change the base image instead!";  exit 1; \
  fi; \
  pip install --no-cache-dir -q -r requirements.txt

# Copy entire project directory
ONBUILD COPY . .
